rootProject.name = "Kmp"

pluginManagement {
    includeBuild("build-logic")
    repositories {
        google {
            mavenContent {
                includeGroupAndSubgroups("androidx")
                includeGroupAndSubgroups("com.android")
                includeGroupAndSubgroups("com.google")
            }
        }
        mavenCentral()
        gradlePluginPortal()
    }
}

dependencyResolutionManagement {
    repositories {
        google {
            mavenContent {
                includeGroupAndSubgroups("androidx")
                includeGroupAndSubgroups("com.android")
                includeGroupAndSubgroups("com.google")
            }
        }
        mavenCentral()
    }
}

plugins {
    id("org.gradle.toolchains.foojay-resolver-convention") version "1.0.0"
}

// Platform entry points
include(":app:androidApp")
include(":app:desktopApp")
include(":app:shared")
include(":app:webApp")

// Architecture layers.
// Dependency direction is strictly inward:
//   :presentation -> :domain
//   :data         -> :domain, :network, :concurrency
//   :domain       -> (nothing)
//   :network      -> (nothing)
//   :concurrency  -> (nothing)
include(":presentation")
include(":domain")
include(":data")
include(":network")
include(":concurrency")

// Sample code generated by the IDE wizard, outside the architecture above.
include(":core")
include(":server")
