import java.io.File

// Executable architecture rules. Applied to the root project only.
//
// moduleGraph below is the single source of truth for module boundaries. It is
// used for two things at once:
//
//  1. `architectureCheck` fails the build when a module's declared project
//     dependencies differ from this map in either direction.
//  2. `architectureDocs` regenerates the graph block inside docs/ARCHITECTURE.md,
//     and `architectureDocsCheck` fails when the committed copy is stale.
//
// That pairing is deliberate. A rule written only in prose rots; a rule written
// only in the build is invisible. Deriving the prose from the rule means changing
// the architecture requires editing exactly one place, and forgetting to update
// the documentation is a build failure rather than a code review nit.

// -----------------------------------------------------------------------------
// THE source of truth. Edit this map to change the architecture.
// -----------------------------------------------------------------------------
val moduleGraph: Map<String, Set<String>> =
    linkedMapOf(
        ":contract" to emptySet(),
        ":core:domain" to emptySet(),
        ":core:concurrency" to emptySet(),
        ":core:network" to setOf(":contract"),
        ":core:data" to setOf(":core:domain", ":core:network", ":core:concurrency"),
        ":presentation" to setOf(":core:domain"),
        ":app:shared" to
            setOf(
                ":presentation",
                ":core:domain",
                ":core:data",
                ":core:network",
                ":core:concurrency",
            ),
        ":app:androidApp" to setOf(":app:shared"),
        ":app:desktopApp" to setOf(":app:shared"),
        ":app:webApp" to setOf(":app:shared"),
        ":server" to setOf(":contract"),
    )

// One line per module, stating what does *not* belong in it.
val moduleCharters: Map<String, String> =
    linkedMapOf(
        ":contract" to
            "Serializable wire models and endpoint paths shared with the server. No logic.",
        ":core:domain" to
            "Business policy. Zero dependencies, not even coroutines or a DI framework.",
        ":core:concurrency" to
            "Dispatchers. If it is not a CoroutineDispatcher or a scope, it goes elsewhere.",
        ":core:network" to
            "Wire mechanics: HTTP, JSON, ApiResult. Nothing that knows what the data means.",
        ":core:data" to
            "Implements domain ports. The only place a DTO and a domain model may meet.",
        ":presentation" to
            "Everything that knows a screen exists. Nothing that knows a network exists.",
        ":app:shared" to
            "Composition root. Wires DI modules and hosts navigation. No logic of its own.",
        ":app:androidApp" to "Android entry point and platform config only.",
        ":app:desktopApp" to "Desktop entry point and packaging only.",
        ":app:webApp" to "Web entry point only.",
        ":server" to "Ktor server. Shares the wire contract with the clients.",
    )

private val generatedStart = "<!-- ARCHITECTURE-GRAPH:START -->"
private val generatedEnd = "<!-- ARCHITECTURE-GRAPH:END -->"

// Captured as plain values so the task actions stay configuration-cache safe:
// the lambdas below must not reach back into Project at execution time.
val rootDirectory: File = rootDir
val architectureDoc: File = File(rootDir, "docs/ARCHITECTURE.md")
val graph: Map<String, Set<String>> = moduleGraph
val charters: Map<String, String> = moduleCharters

// Renders the generated documentation block from moduleGraph.
fun renderGraphBlock(
    graph: Map<String, Set<String>>,
    charters: Map<String, String>,
): String = buildString {
    appendLine(generatedStart)
    appendLine()
    appendLine("<!--")
    appendLine("  Generated by ./gradlew architectureDocs from moduleGraph in")
    appendLine("  build-logic/src/main/kotlin/kmp.architecture.gradle.kts.")
    appendLine("  Do not edit by hand: architectureDocsCheck fails when this block is stale.")
    appendLine("-->")
    appendLine()
    appendLine("| Module | May depend on | Charter |")
    appendLine("| --- | --- | --- |")
    graph.forEach { (module, deps) ->
        val depText = if (deps.isEmpty()) "_nothing_" else deps.sorted().joinToString(", ") { "`$it`" }
        appendLine("| `$module` | $depText | ${charters[module] ?: ""} |")
    }
    appendLine()
    appendLine("```mermaid")
    appendLine("graph TD")
    graph.forEach { (module, deps) ->
        if (deps.isEmpty()) {
            appendLine("  \"$module\"")
        } else {
            deps.sorted().forEach { dep -> appendLine("  \"$module\" --> \"$dep\"") }
        }
    }
    appendLine("```")
    appendLine()
    append(generatedEnd)
}

tasks.register("architectureCheck") {
    group = "verification"
    description = "Fails when module dependencies differ from moduleGraph."

    // Always runs: the cost is a handful of small file reads, and a stale
    // "up to date" result on a correctness gate is worse than the runtime.
    outputs.upToDateWhen { false }

    val root = rootDirectory
    val expected = graph

    doLast {
        val projectRef = Regex("""project\("(:[^"]+)"\)""")
        val problems = mutableListOf<String>()

        expected.forEach { (module, allowed) ->
            val relative = module.removePrefix(":").replace(':', '/')
            val buildFile = File(root, "$relative/build.gradle.kts")

            if (!buildFile.isFile) {
                problems += "$module: no build.gradle.kts at $relative/"
                return@forEach
            }

            val declared =
                buildFile
                    .readLines()
                    .map { line -> line.substringBefore("//") }
                    .flatMap { line -> projectRef.findAll(line).map { it.groupValues[1] } }
                    .toSet()

            (declared - allowed).sorted().forEach { forbidden ->
                problems += "$module must not depend on $forbidden"
            }
            (allowed - declared).sorted().forEach { missing ->
                problems += "$module no longer depends on $missing, so moduleGraph is stale"
            }
        }

        // Every module in settings.gradle.kts must have a charter. This is what
        // stops a new module appearing without anyone deciding where it sits.
        val includeRef = Regex("""include\("(:[^"]+)"\)""")
        val settingsFile = File(root, "settings.gradle.kts")
        val included =
            settingsFile
                .readLines()
                .map { line -> line.substringBefore("//") }
                .flatMap { line -> includeRef.findAll(line).map { it.groupValues[1] } }
                .toSet()

        (included - expected.keys).sorted().forEach { module ->
            problems += "$module is in settings.gradle.kts but has no entry in moduleGraph"
        }
        (expected.keys - included).sorted().forEach { module ->
            problems += "$module is in moduleGraph but not included in settings.gradle.kts"
        }

        if (problems.isNotEmpty()) {
            error(
                buildString {
                    appendLine("Architecture rules violated:")
                    problems.forEach { appendLine("  - $it") }
                    appendLine()
                    appendLine("Dependencies must match moduleGraph in")
                    appendLine("build-logic/src/main/kotlin/kmp.architecture.gradle.kts.")
                    appendLine(
                        "If the new dependency is intentional, update that map, run " +
                            "./gradlew architectureDocs, and record an ADR in docs/adr/.",
                    )
                },
            )
        }
    }
}

tasks.register("architectureDocs") {
    group = "documentation"
    description = "Regenerates the module graph block in docs/ARCHITECTURE.md."

    outputs.upToDateWhen { false }

    val doc = architectureDoc
    val block = renderGraphBlock(graph, charters)
    val start = generatedStart
    val end = generatedEnd

    doLast {
        require(doc.isFile) { "Missing ${doc.path}" }
        val text = doc.readText()
        val startIndex = text.indexOf(start)
        val endIndex = text.indexOf(end)
        require(startIndex >= 0 && endIndex > startIndex) {
            "${doc.path} must contain the $start / $end markers"
        }
        val updated = text.substring(0, startIndex) + block + text.substring(endIndex + end.length)
        if (updated != text) {
            doc.writeText(updated)
            logger.lifecycle("Updated ${doc.path}")
        }
    }
}

tasks.register("architectureDocsCheck") {
    group = "verification"
    description = "Fails when docs/ARCHITECTURE.md no longer matches moduleGraph."

    outputs.upToDateWhen { false }

    val doc = architectureDoc
    val block = renderGraphBlock(graph, charters)
    val start = generatedStart
    val end = generatedEnd

    doLast {
        require(doc.isFile) { "Missing ${doc.path}" }
        val text = doc.readText()
        val startIndex = text.indexOf(start)
        val endIndex = text.indexOf(end)
        require(startIndex >= 0 && endIndex > startIndex) {
            "${doc.path} must contain the $start / $end markers"
        }
        val current = text.substring(startIndex, endIndex + end.length)
        if (current != block) {
            error(
                "docs/ARCHITECTURE.md is out of date with moduleGraph. " +
                    "Run ./gradlew architectureDocs and commit the result.",
            )
        }
    }
}

tasks.register("conventionsCheck") {
    group = "verification"
    description = "Greps for conventions the compiler cannot express."

    outputs.upToDateWhen { false }

    val root = rootDirectory

    doLast {
        val problems = mutableListOf<String>()

        fun sourceFiles(): List<File> = root
            .walkTopDown()
            .onEnter { dir ->
                dir.name !in setOf("build", ".git", ".gradle", ".kotlin", "node_modules", ".idea")
            }.filter { it.isFile }
            .toList()

        val files = sourceFiles()

        // Comments are stripped first: documentation is allowed to *discuss* a
        // banned API, it just may not call it.
        val blockComment = Regex("""/\*[\s\S]*?\*/""")
        val lineComment = Regex("""//.*""")

        fun code(file: File): String = file.readText().replace(blockComment, "").replace(lineComment, "")

        // Dispatchers.IO does not exist on JS or Wasm and is internal on Native.
        // The only legitimate references are the platform actuals in :core:concurrency.
        files
            .filter { it.extension == "kt" }
            .filter { !it.path.replace('\\', '/').contains("core/concurrency/src/") }
            .filter { code(it).contains("Dispatchers.IO") }
            .forEach {
                problems += "${it.relativeTo(root).path}: references Dispatchers.IO. " +
                    "Inject DispatcherProvider instead (see docs/KMP_PITFALLS.md)."
            }

        // Versions belong in gradle/libs.versions.toml, never inline.
        val inlineCoordinate =
            Regex(
                """(?:implementation|api|testImplementation|compileOnly|runtimeOnly)""" +
                    """\(\s*"[\w.\-]+:[\w.\-]+:[\w.\-]+"""",
            )
        files
            .filter { it.name.endsWith(".gradle.kts") }
            .forEach { file ->
                file.readLines().forEachIndexed { index, line ->
                    if (inlineCoordinate.containsMatchIn(line.substringBefore("//"))) {
                        problems += "${file.relativeTo(root).path}:${index + 1}: " +
                            "hardcoded dependency version. Use gradle/libs.versions.toml."
                    }
                }
            }

        if (problems.isNotEmpty()) {
            error(
                buildString {
                    appendLine("Convention violations:")
                    problems.forEach { appendLine("  - $it") }
                },
            )
        }
    }
}
